### ISSUE TITLE
fix subreddit stuff 

### ISSUE THREAD

**Issue by atiwiex** [4Kaylum/Spar.cli#1]
**My mouse is broken**

**Comment by 4Kaylum** [comment]
"subreddit stuff" referring to using the `subreddit` command on a sub that doesn't exist. The same issue may also occur for users - note to self: check this.

**Comment by 4Kaylum** [comment]
Closed as of [this commit](https://github.com/4Kaylum/Spar.cli/commit/10472777d2b04eec4379dfac53f21e7d4ffed482).
